const startTagOptions=[{id:'normal',label:'通常ヒット',color:'#58708f'},{id:'counter',label:'カウンターヒット',color:'#d94a55'},{id:'heat-dash',label:'ヒートダッシュ',color:'#b14ed0'},{id:'wall',label:'壁コンボ',color:'#d27a32'},{id:'low-parry',label:'下段捌き',color:'#3f9b78'},{id:'ground',label:'地上コンボ',color:'#6d65c7'}];
const stringConditionOptions=[{id:'after-guard',label:'ガード後',color:'#247584'},{id:'after-hit',label:'ヒット後',color:'#347c65'},{id:'after-counter',label:'カウンターヒット後',color:'#8b4b72'}];
const characterConditions={
  '仁':[['前心','前心']],
  'キング':[['ジャガースプリント','JSP'],['ジャガーステップ','JST']],
  '準':[['出雲','出雲'],['幻日','幻日'],['御阿礼','御阿礼']],
  'ポール':[['二重潜り','二重潜り']],
  'ロウ':[['チャージドラゴン','CD']],
  'ジャック8':[['ガンマハウリング','GH']],
  'ラース':[['サイレント・エントリー','SE'],['ダイナミック・エントリー','DE'],['リミテッド・エントリー','LE']],
  'シャオユウ':[['擺歩','擺歩'],['鳳凰','鳳凰']],
  'ニーナ':[['スウェー','スウェー']],
  'リロイ':[['独歩','独歩']],
  '飛鳥':[['浪花の気焔保持','気焔保持']],
  'リリ':[['バラードステップ','BS']],
  'ブライアン':[['スネークアイ保持','スネークアイ']],
  'ファラン':[['右構え','右構え'],['ライトフラミンゴ','RF'],['レフトフラミンゴ','LF']],
  'クラウディオ':[['スターバースト保持','スターバースト']],
  'アズセナ':[['リベルタドール','LD']],
  'レイヴン':[['ソウルフィールド','SF']],
  'レオ':[['閃電保持','閃電保持'],['金鶏','金鶏'],['仆歩','仆歩']],
  'スティーブ':[['ウィービング・レフト','WL'],['ウィービング・ライト','WR'],['クイックターン','QT'],['ダッキング','DUK'],['ロング・ダッキング','LDK'],['ピーカブースタイル','PKB'],['スウェー','SW'],['フリッカー','FLC'],['ライオンハート','LH']],
  'クマ':[['ハンティングスタイル','HS'],['ベアシット','BS'],['ベアロール','BR']],
  'パンダ':[['ハンティングスタイル','HS'],['ベアシット','BS'],['ベアロール','BR']],
  '吉光':[['無刀ノ極','無刀'],['金打','金打'],['地雷刃','地雷刃'],['卍あぐら','卍あぐら'],['卍蜻蛉','卍蜻蛉']],
  'シャヒーン':[['スネークイン','SI']],
  'ドラグノフ':[['ローリングエスケープ','RE']],
  'フェン':[['雲手','雲手'],['虚歩','虚歩']],
  'リー':[['ヒットマン・スタイル','HS'],['ミスト・ステップ','MS']],
  'アリサ':[['デストロイフォーム','DF'],['ブート','BT'],['デュアルブート','DB'],['バックアップ','BU']],
  'ザフィーナ':[['モード・スケアクロウ','MS'],['モード・タランチュラ','MT'],['モード・マンティス','MM'],['アナセマ保持','アナセマ']],
  'デビル仁':[['飛空','飛空'],['忌鴉','忌鴉']],
  'ヴィクター':[['イアイ・ポズィション','IP'],['パフューマー','Pf']],
  '麗奈':[['旋体','旋体'],['運足','運足'],['金剛壁','金剛壁']],
  'エディ':[['バナネイラ','BN'],['ネガチーヴァ','NG'],['マンジンガLv.1所持','M1'],['マンジンガLv.2所持','M2']],
  'リディア':[['天上天下の構え','天上天下'],['天上天下レベル1','Lv.1'],['天上天下レベル2','Lv.2'],['天上天下レベル3','Lv.3'],['前虎後狼の構え','前虎後狼'],['猫足','猫足'],['騎馬立ち','騎馬立ち']],
  '平八':[['風神呼法','風神呼法'],['雷神呼法','雷神呼法'],['武の境地時','武の境地']],
  'クライヴ':[['バハムートウィング','BW'],['フェニックスシフト','PS'],['アップドラフト','UD']],
  'アンナ':[['ハンマーチャンス','HC'],['カオスジャッジメント','CJ'],['プレジャータイム','PT']],
  'ファーカムラム':[['ガルーダフォース保持','GF']],
  'アーマーキング':[['バッドジャガー','BJ']],
  'ミアリズ':[['モラング・ミルス','MM'],['バオバブ・ミール','BM']],
  '州光':[['華遁','華遁'],['刹那駆け','刹那駆け']],
  'ボブ':[['スピナーボール','SB']]
};
const groups={direction:['7','8','9','4','☆','6','1','2','3'],attack:['LP','RP','LK','RK','WP','WK','LP+LK','RP+RK','RP+LK','LP+RK'],special:[],separator:['>'],slide:['【','】'],movement:['前ステ','バクステ','右横移動','左横移動'],state:['立ち途中','横移動中','しゃがみ中','背向け'],stateTag:['相手ダウン中','ヒート中','壁やられ中'],stage:['壁到達','壁強','ウォールブレイク','フロアブレイク'],system:['トルネード','ヒートバースト','ヒートスマッシュ','ヒートダッシュ','レイジアーツ']};
const titles={direction:'方向',attack:'攻撃',special:'キャラクター固有',separator:'技の区切り',slide:'スライド入力',movement:'移動',state:'入力状態',stateTag:'状態タグ',stage:'壁・ステージ',system:'システム'};
const named={'最風':['最風','最速風神拳'],'前ステ':['66','前ステ'],'バクステ':['44','バクステ'],'右横移動':['右横','右横移動'],'左横移動':['左横','左横移動'],'立ち途中':['立ち途中','立ち途中'],'横移動中':['横移動中','横移動中'],'しゃがみ中':['しゃがみ中','しゃがみ中'],'背向け':['背向け','背向け'],'壁到達':['W!','壁到達'],'壁強':['W強','壁強'],'ウォールブレイク':['WB','ウォールブレイク'],'フロアブレイク':['FB','フロアブレイク'],'トルネード':['T!','トルネード'],'ヒートバースト':['HB','ヒートバースト'],'ヒートスマッシュ':['HS','ヒートスマッシュ'],'ヒートダッシュ':['HD','ヒートダッシュ'],'レイジアーツ':['RA','レイジアーツ']};
const arrows={'7':'↖','8':'↑','9':'↗','4':'←','☆':'●','6':'→','1':'↙','2':'↓','3':'↘'};
const attackDots={LP:[1,0,0,0],RP:[0,1,0,0],LK:[0,0,1,0],RK:[0,0,0,1],WP:[1,1,0,0],WK:[0,0,1,1],'LP+LK':[1,0,1,0],'RP+RK':[0,1,0,1],'RP+LK':[0,1,1,0],'LP+RK':[1,0,0,1],'LP+LK+RK':[1,0,1,1]};
function attackPad(label){const dots=attackDots[label]||[0,0,0,0];return `<span class="attack-pad" aria-hidden="true">${dots.map(on=>`<i class="${on?'on':''}"></i>`).join('')}</span><small class="attack-label">${label}</small>`}
function iconHtml(label,type,hold=false){if(type==='direction')return `<span class="dir-icon ${label==='☆'?'neutral':`d${label}`} ${hold?'held':''}">${label==='☆'?'☆':'➜'}</span>`;if(type==='attack')return `<span class="attack-set">${attackPad(label)}</span>`;return label}
let combo=[],lastTap=0,timer,directionMode='tap',selectedStartTag=startTagOptions[0],selectedStringCondition=stringConditionOptions[0],currentMode='combo',selectedIndex=null,currentRecipeId=null;const $=s=>document.querySelector(s),controls=$('#controls');
const recipeStorageKey='ccm-recipes-v1';let savedRecipes=[];try{savedRecipes=JSON.parse(localStorage.getItem(recipeStorageKey)||'[]');if(!Array.isArray(savedRecipes))savedRecipes=[]}catch(error){savedRecipes=[]}
const mainCharacterStorageKey='ccm-main-character-v1';let mainCharacter='一八';try{mainCharacter=localStorage.getItem(mainCharacterStorageKey)||'一八'}catch(error){mainCharacter='一八'}
function activeContextTag(){return currentMode==='combo'?selectedStartTag:selectedStringCondition}
function renderStartTag(){const activeTag=activeContextTag();['#liveStartTag','#cardStartTag'].forEach(selector=>{const el=$(selector);el.textContent=activeTag.label;el.style.setProperty('--tag-color',activeTag.color)});document.querySelectorAll('.start-choice').forEach(button=>{const active=button.dataset.tag===selectedStartTag.id;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});document.querySelectorAll('.condition-choice').forEach(button=>{const active=button.dataset.condition===selectedStringCondition.id;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))})}
startTagOptions.forEach(tag=>{const button=document.createElement('button');button.className='start-choice';button.dataset.tag=tag.id;button.style.setProperty('--tag-color',tag.color);button.textContent=tag.label;button.onclick=()=>{selectedStartTag=tag;renderStartTag();persistCurrentRecipe();say(`${tag.label}を選択`)};$('#startTags').append(button)});renderStartTag();
stringConditionOptions.forEach(condition=>{const button=document.createElement('button');button.className='condition-choice';button.dataset.condition=condition.id;button.textContent=condition.label;button.onclick=()=>{selectedStringCondition=condition;renderStartTag();persistCurrentRecipe();say(`${condition.label}を選択`)};$('#stringConditions').append(button)});
function renderMode(){const stringMode=currentMode==='string';document.body.dataset.cardMode=currentMode;$('#comboMode').classList.toggle('active',!stringMode);$('#stringMode').classList.toggle('active',stringMode);$('#stringConditionPanel').hidden=!stringMode;$('#cardTypeLabel').textContent=stringMode?'連携':'COMBO GUIDE';$('#notesLabel').textContent=stringMode?'連携用メモ':'POINT・注釈';$('#cardNotesLabel').textContent=stringMode?'連携メモ':'POINT';$('#notes').placeholder=stringMode?'例：+5F／二択／壁際限定':'例：トルネード後は少し前ステ';if(!$('#notes').value.trim())$('#cardNotes').textContent=stringMode?'連携メモを入力するとここに表示されます。':'注釈を入力するとここに表示されます。';if(!combo.length)$('#cardCombo').textContent=stringMode?'連携未入力':'コンボ未入力';$('#cardCombo').setAttribute('aria-label',`${stringMode?'連携':'コンボ'}。ダブルタップで直前の入力を削除`);$('#save').textContent=isMobile&&stringMode?'↓ 連携画像を保存・共有':isMobile?'↓ コンボ画像を保存・共有':stringMode?'↓ 連携画像を保存':'↓ コンボ画像を保存';renderStartTag();persistCurrentRecipe()}
Object.entries(groups).forEach(([type,items])=>{const group=document.createElement('div');group.className='group';group.innerHTML=`<div class="group-title">${titles[type]}</div>${type==='direction'?'<div class="direction-mode"><button class="active" data-mode="tap">白抜き・短押し</button><button data-mode="hold">黒・長押し</button></div>':''}<div class="grid ${type==='direction'?'':'two'}"></div>`;const grid=group.querySelector('.grid'),buttons=[];items.forEach(label=>{const b=document.createElement('button');b.className=`cmd ${type}`;const paint=()=>b.innerHTML=iconHtml(label,type,directionMode==='hold');paint();buttons.push(paint);b.setAttribute('aria-label',`${label}を追加`);b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),110);const wasHold=type==='direction'&&directionMode==='hold';combo.push({label,type,hold:wasHold});render();say(`${label}${wasHold?'長押し':''} を追加`);if(wasHold){directionMode='tap';group.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode==='tap'));buttons.forEach(p=>p())}};grid.append(b)});if(type==='direction')group.querySelectorAll('[data-mode]').forEach(tab=>tab.onclick=()=>{directionMode=tab.dataset.mode;group.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===tab));buttons.forEach(p=>p())});controls.append(group)});
const mishimaCharacters=new Set(['一八','デビル仁','麗奈','平八']);
const holdAnnotationCharacters=new Set(['アリサ','アーマーキング','飛鳥','ブライアン','クラウディオ','クライヴ','デビル仁','ファーカムラム','フェン','平八','ジャック8','一八','キング','クマ','パンダ','リー','リディア','ニーナ','ポール','ヴィクター','吉光','麗奈','ラース','リリ','ボブ','シャオユウ']);
const justAnnotationCharacters=new Set(['ドラグノフ','ファーカムラム','平八','ファラン','リー','ロウ','ボブ']);
const guardBreakCharacters=new Set(['クラウディオ','クライヴ','デビル仁','フェン','平八','ジャック8','キング','クマ','パンダ','ポール','麗奈','スティーブ','吉光']);
function updateCharacterCommands(){const character=$('#character').value,special=controls.children[2],grid=special?.querySelector('.grid');if(!grid)return;const items=[...(mishimaCharacters.has(character)?[['最速風神拳','最風']]:[]),...(characterConditions[character]||[])];special.hidden=!items.length;grid.innerHTML='';items.forEach(([label,code])=>{const button=document.createElement('button');button.className='cmd special';button.innerHTML=`<strong>${code}</strong><small>${label}</small>`;button.setAttribute('aria-label',`${label}を追加`);button.onclick=()=>{button.classList.add('pressed');setTimeout(()=>button.classList.remove('pressed'),110);combo.push({label,type:'special',code,caption:label});render();say(`${label}を追加`)};grid.append(button)})}
function updateCharacterAttacks(){const character=$('#character').value,grid=controls.children[1]?.querySelector('.grid');if(!grid)return;const items=['LP','RP','LK','RK','WP','WK','LP+LK','RP+RK','RP+LK','LP+RK',...(character==='ブライアン'?['LP+LK+RK']:[])];grid.innerHTML='';items.forEach(label=>{const button=document.createElement('button');button.className='cmd attack';button.innerHTML=iconHtml(label,'attack');button.setAttribute('aria-label',label==='LP+LK+RK'?'挑発（LP+LK+RK）を追加':`${label}を追加`);button.onclick=()=>{button.classList.add('pressed');setTimeout(()=>button.classList.remove('pressed'),110);combo.push({label,type:'attack'});render();say(label==='LP+LK+RK'?'挑発を追加':`${label}を追加`)};grid.append(button)})}
function updateCharacterStateTags(){const character=$('#character').value,group=controls.children[7],grid=group?.querySelector('.grid');if(!grid)return;const items=['相手ダウン中','ヒート中','壁やられ中',...(guardBreakCharacters.has(character)?['ガードブレイク']:[])];grid.innerHTML='';items.forEach(label=>{const button=document.createElement('button');button.className='cmd stateTag';button.textContent=label;button.setAttribute('aria-label',`${label}を追加`);button.onclick=()=>{button.classList.add('pressed');setTimeout(()=>button.classList.remove('pressed'),110);combo.push({label,type:'stateTag'});render();say(`${label}を追加`)};grid.append(button)})}
function canEdit(item){return !['separator','stateTag','slide'].includes(item.type)}
function decorateItem(el,item,index){if(item.count>1){const count=document.createElement('b');count.className='count-badge';count.textContent=`×${item.count}`;el.append(count)}if(item.annotations?.length){const notes=document.createElement('span');notes.className='item-annotations';notes.textContent=item.annotations.join('・');el.append(notes)}if(canEdit(item)){el.classList.add('editable-token');el.classList.toggle('selected-token',selectedIndex===index);el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`${item.label}を編集`);const choose=e=>{e.stopPropagation();selectedIndex=index;updateEditor();render()};el.onclick=choose;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(e)}}}}
function draw(el,empty){el.innerHTML='';if(!combo.length){el.textContent=empty;return}combo.forEach((item,index)=>{let x=document.createElement('span');if(item.type==='separator'){x.className='sep';x.textContent='>'}else if(item.type==='stateTag'){x.className='state-tag';x.textContent=item.label}else if(item.code||named[item.label]){x.className='named';x.innerHTML=`<span>${item.code||named[item.label][0]}</span><small>${item.caption||named[item.label][1]}</small>`}else{x.className=`token ${item.type}-token`;x.innerHTML=iconHtml(item.label,item.type,item.hold)}decorateItem(x,item,index);el.append(x)})}
function recipeSnapshot(id,title){return{id,title,updatedAt:Date.now(),mode:currentMode,character:$('#character').value,damage:$('#damage').value,difficulty:$('#difficulty').value,notes:$('#notes').value,startTagId:selectedStartTag.id,stringConditionId:selectedStringCondition.id,combo:JSON.parse(JSON.stringify(combo))}}
function storeRecipes(){try{localStorage.setItem(recipeStorageKey,JSON.stringify(savedRecipes))}catch(error){say('端末の保存領域を利用できませんでした')}}
function updateMainCharacterUI(){const button=$('#setMainCharacter'),selected=$('#character').value,isMain=selected===mainCharacter;button.textContent=isMain?`★ ${selected}（メイン）`:'☆ このキャラをメインに設定';button.classList.toggle('active',isMain);button.disabled=isMain}
function setMainCharacter(){mainCharacter=$('#character').value;try{localStorage.setItem(mainCharacterStorageKey,mainCharacter)}catch(error){say('メインキャラクターを保存できませんでした');return}updateMainCharacterUI();say(`${mainCharacter}をメインキャラクターに設定しました`)}
function persistCurrentRecipe(){if(!currentRecipeId)return;const at=savedRecipes.findIndex(recipe=>recipe.id===currentRecipeId);if(at<0)return;savedRecipes[at]=recipeSnapshot(currentRecipeId,savedRecipes[at].title);storeRecipes();renderRecipeList()}
function renderRecipeList(){const library=$('#recipeLibrary'),list=$('#recipeList');library.hidden=!savedRecipes.length;list.innerHTML='';savedRecipes.forEach(recipe=>{const row=document.createElement('div');row.className=`recipe-row ${recipe.id===currentRecipeId?'active':''}`;const isString=recipe.mode==='string',contextLabel=isString?(stringConditionOptions.find(condition=>condition.id===recipe.stringConditionId)?.label||'ガード後'):(recipe.startTagLabel||startTagOptions.find(tag=>tag.id===recipe.startTagId)?.label||'通常ヒット');const info=document.createElement('div');info.innerHTML=`<strong>${recipe.title}</strong><small>${isString?'連携・':''}${contextLabel}・${recipe.combo?.length||0}入力</small>`;const actions=document.createElement('div');actions.className='recipe-actions';const open=document.createElement('button');open.textContent=recipe.id===currentRecipeId?'編集中':'開く';open.disabled=recipe.id===currentRecipeId;open.onclick=()=>loadRecipe(recipe.id);const remove=document.createElement('button');remove.className='recipe-delete';remove.textContent='削除';remove.onclick=()=>deleteRecipe(recipe.id);actions.append(open,remove);row.append(info,actions);list.append(row)})}
function deleteRecipe(id){const recipe=savedRecipes.find(item=>item.id===id);if(!recipe)return;if(!confirm(`「${recipe.title}」を保存一覧から削除しますか？`))return;savedRecipes=savedRecipes.filter(item=>item.id!==id);if(currentRecipeId===id)currentRecipeId=null;storeRecipes();renderRecipeList();say(`${recipe.title}を削除しました`)}
function loadRecipe(id){persistCurrentRecipe();const recipe=savedRecipes.find(item=>item.id===id);if(!recipe)return;currentRecipeId=id;combo=JSON.parse(JSON.stringify(recipe.combo||[]));selectedIndex=null;currentMode=recipe.mode||'combo';selectedStartTag=startTagOptions.find(tag=>tag.id===recipe.startTagId)||startTagOptions[0];selectedStringCondition=stringConditionOptions.find(condition=>condition.id===recipe.stringConditionId)||stringConditionOptions[0];$('#character').value=recipe.character||'一八';$('#damage').value=recipe.damage||'0';$('#difficulty').value=recipe.difficulty||'★☆☆☆☆';$('#notes').value=recipe.notes||'';$('#cardCharacter').textContent=$('#character').value;$('#cardDamage').textContent=$('#damage').value;$('#cardDifficulty').textContent=$('#difficulty').value;$('#cardNotes').textContent=$('#notes').value.trim()||(currentMode==='string'?'連携メモを入力するとここに表示されます。':'注釈を入力するとここに表示されます。');renderMode();updateCharacterAttacks();updateCharacterCommands();updateCharacterStateTags();updateMainCharacterUI();updateEditor();render();renderRecipeList();say(`${recipe.title}を開きました`)}
function copyRecipe(){if(!combo.length)return say(`コピーする${currentMode==='string'?'連携':'コンボ'}を入力してください`);persistCurrentRecipe();const stamp=Date.now(),character=$('#character').value||'レシピ',kind=currentMode==='string'?'連携':'コンボ';if(!currentRecipeId){const original=recipeSnapshot(`recipe-${stamp}`,`${character} ${kind} 基本`);savedRecipes.push(original)}const clone=recipeSnapshot(`recipe-${stamp+1}`,`${character} ${kind} コピー`);savedRecipes.push(clone);currentRecipeId=clone.id;storeRecipes();renderRecipeList();say('元を残してレシピをコピーしました')}
function render(){draw($('#live'),'ここを見ながら入力できます');draw($('#cardCombo'),currentMode==='string'?'連携未入力':'コンボ未入力');persistCurrentRecipe()}
function say(t){$('#status').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent=combo.length?`${combo.length}入力`:'コマンドを入力してください',900)}
function updateEditor(){const item=combo[selectedIndex],editor=$('#commandEditor');if(!item||!canEdit(item)){selectedIndex=null;editor.hidden=true;return}editor.hidden=false;$('#selectedCommand').textContent=item.label;document.querySelectorAll('.count-choice').forEach(button=>button.classList.toggle('active',Number(button.dataset.count)===(item.count||1)));$('#delayAnnotation').classList.toggle('active',item.annotations?.includes('ディレイ')||false);const charge=$('#chargeAnnotation'),chargeEligible=$('#character').value==='シャヒーン'&&item.type==='direction'&&['1','2','3'].includes(item.label);charge.hidden=!chargeEligible;charge.classList.toggle('active',chargeEligible&&(item.annotations?.includes('溜め')||false));const hold=$('#holdAnnotation'),holdEligible=holdAnnotationCharacters.has($('#character').value);hold.hidden=!holdEligible;hold.classList.toggle('active',holdEligible&&(item.annotations?.includes('ホールド')||false));const just=$('#justAnnotation'),justEligible=justAnnotationCharacters.has($('#character').value);just.hidden=!justEligible;just.classList.toggle('active',justEligible&&(item.annotations?.includes('ジャスト')||false))}
function undo(){if(!combo.length)return say('これ以上戻せません');const x=combo.pop();if(selectedIndex!==null&&selectedIndex>=combo.length)selectedIndex=null;updateEditor();render();say(`${x.label} を削除`)}
$('#undo').onclick=undo;$('#copyRecipe').onclick=copyRecipe;$('#clear').onclick=()=>{if(combo.length&&confirm('入力したコンボを全て消しますか？')){combo=[];selectedIndex=null;updateEditor();render();say('全て削除しました')}};$('#toggle').onclick=()=>{const hidden=controls.hidden;controls.hidden=!hidden;$('#toggle').setAttribute('aria-expanded',hidden);$('#chevron').textContent=hidden?'▲':'▼'};
document.querySelectorAll('.count-choice').forEach(button=>button.onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.count=Number(button.dataset.count);updateEditor();render();say(item.count>1?`${item.label}を×${item.count}に設定`:`${item.label}の回数を解除`)});
$('#delayAnnotation').onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.annotations=item.annotations||[];const at=item.annotations.indexOf('ディレイ');if(at>=0)item.annotations.splice(at,1);else item.annotations.push('ディレイ');updateEditor();render();say(at>=0?'ディレイを解除':'ディレイを追加')};
$('#chargeAnnotation').onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.annotations=item.annotations||[];const at=item.annotations.indexOf('溜め');if(at>=0)item.annotations.splice(at,1);else item.annotations.push('溜め');updateEditor();render();say(at>=0?'溜めを解除':'溜めを追加')};
$('#holdAnnotation').onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.annotations=item.annotations||[];const at=item.annotations.indexOf('ホールド');if(at>=0)item.annotations.splice(at,1);else item.annotations.push('ホールド');updateEditor();render();say(at>=0?'ホールドを解除':'ホールドを追加')};
$('#justAnnotation').onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.annotations=item.annotations||[];const at=item.annotations.indexOf('ジャスト');if(at>=0)item.annotations.splice(at,1);else item.annotations.push('ジャスト');updateEditor();render();say(at>=0?'ジャストを解除':'ジャストを追加')};
$('#onlyHitAnnotation').onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.annotations=(item.annotations||[]).filter(note=>!note.endsWith('発目のみヒット'));item.annotations.push(`${$('#hitNumber').value}発目のみヒット`);updateEditor();render();say(`${$('#hitNumber').value}発目のみヒットを追加`)};
$('#clearAnnotations').onclick=()=>{const item=combo[selectedIndex];if(!item)return;item.annotations=[];updateEditor();render();say('技注釈を外しました')};$('#closeEditor').onclick=()=>{selectedIndex=null;updateEditor();render()};
$('#cardCombo').addEventListener('pointerup',()=>{const now=Date.now();if(now-lastTap<360){lastTap=0;undo()}else lastTap=now});$('#cardCombo').ondblclick=e=>{e.preventDefault();undo()};$('#cardCombo').onkeydown=e=>{if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();undo()}};
[['#character','#cardCharacter','CHARACTER'],['#damage','#cardDamage','0'],['#difficulty','#cardDifficulty','★☆☆☆☆']].forEach(([a,b,f])=>{const input=$(a),out=$(b),update=()=>out.textContent=String(input.value).trim()||f;input.oninput=update;input.onchange=update});$('#notes').oninput=e=>$('#cardNotes').textContent=e.target.value.trim()||(currentMode==='string'?'連携メモを入力するとここに表示されます。':'注釈を入力するとここに表示されます。');render();
if(![...$('#character').options].some(option=>option.value===mainCharacter))mainCharacter='一八';$('#character').value=mainCharacter;$('#cardCharacter').textContent=mainCharacter;$('#setMainCharacter').onclick=setMainCharacter;$('#character').addEventListener('change',updateCharacterAttacks);$('#character').addEventListener('change',updateCharacterCommands);$('#character').addEventListener('change',updateCharacterStateTags);$('#character').addEventListener('change',updateMainCharacterUI);$('#character').addEventListener('change',updateEditor);['#character','#damage','#difficulty','#notes'].forEach(selector=>{$(selector).addEventListener('input',persistCurrentRecipe);$(selector).addEventListener('change',persistCurrentRecipe)});updateCharacterAttacks();updateCharacterCommands();updateCharacterStateTags();updateMainCharacterUI();renderRecipeList();
function wrap(c,text,x,y,maxWidth,lineHeight,maxLines=4){let line='',lines=[];for(const ch of [...text]){const test=line+ch;if(c.measureText(test).width>maxWidth&&line){lines.push(line);line=ch}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>c.fillText(i===maxLines-1&&lines.length>maxLines?l.slice(0,-1)+'…':l,x,y+i*lineHeight))}
function savePng(){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const c=canvas.getContext('2d'),font='"Noto Sans JP","Yu Gothic",sans-serif';c.fillStyle='#080a0d';c.fillRect(0,0,1200,630);const glow=c.createRadialGradient(1050,0,0,1050,0,520);glow.addColorStop(0,'#52171d');glow.addColorStop(1,'#080a0d');c.fillStyle=glow;c.fillRect(0,0,1200,630);c.fillStyle='#e6333e';c.fillRect(55,50,8,530);c.fillStyle='#171d24';c.beginPath();c.roundRect(63,50,1082,530,22);c.fill();c.fillStyle='#f5f7fa';c.font=`900 44px ${font}`;c.fillText($('#character').value.trim()||'CHARACTER',105,125);c.fillStyle='#9ca6b5';c.font=`700 17px ${font}`;c.fillText('COMBO GUIDE',105,155);c.textAlign='right';c.fillText('DAMAGE',1095,92);c.fillStyle='#f1b84b';c.font=`900 58px ${font}`;c.fillText($('#damage').value||'0',1095,148);c.textAlign='left';c.strokeStyle='#2d3540';c.beginPath();c.moveTo(105,184);c.lineTo(1100,184);c.stroke();c.fillStyle='#f5f7fa';c.font=`900 38px ${font}`;wrap(c,combo.map(v=>named[v.label]?.[0]||v.label).join('')||'コンボ未入力',105,255,990,54,3);c.beginPath();c.moveTo(105,410);c.lineTo(1100,410);c.stroke();c.fillStyle='#9ca6b5';c.font=`700 16px ${font}`;c.fillText('難易度',105,455);c.fillText('POINT',340,455);c.fillStyle='#f5f7fa';c.font=`800 25px ${font}`;c.fillText($('#difficulty').value,105,495);c.font=`500 21px ${font}`;wrap(c,$('#notes').value.trim()||'注釈なし',340,493,755,30,3);c.fillStyle='#e6333e';c.font=`900 18px ${font}`;c.fillText('TEKKEN 8 COMBO MAKER',105,552);const a=document.createElement('a'),safe=($('#character').value.trim()||'combo').replace(/[\\/:*?"<>|]/g,'-');a.download=`${safe}-combo.png`;a.href=canvas.toDataURL('image/png');a.click();say('PNGを保存しました')}
$('#save').onclick=savePng;
function canvasArrow(c,x,y,size,dir,filled){const angles={'6':0,'3':45,'2':90,'1':135,'4':180,'7':225,'8':270,'9':315};c.save();c.translate(x+size/2,y+size/2);c.rotate((angles[dir]||0)*Math.PI/180);c.beginPath();c.moveTo(-size*.42,-size*.15);c.lineTo(size*.08,-size*.15);c.lineTo(size*.08,-size*.34);c.lineTo(size*.43,0);c.lineTo(size*.08,size*.34);c.lineTo(size*.08,size*.15);c.lineTo(-size*.42,size*.15);c.closePath();if(filled){c.fillStyle='#f5f7fa';c.fill()}else{c.strokeStyle='#f5f7fa';c.lineWidth=2;c.stroke()}c.restore()}
function canvasAttack(c,x,y,label){const dots=attackDots[label]||[0,0,0,0],r=8,gap=20;dots.forEach((on,i)=>{const cx=x+(i%2)*gap+r,cy=y+Math.floor(i/2)*gap+r;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fillStyle=on?'#f5f7fa':'#171d24';c.fill();c.strokeStyle='#f5f7fa';c.lineWidth=1.8;c.stroke()});c.fillStyle='#b8c0cc';c.font=`800 ${label.length>6?10:14}px "Yu Gothic",sans-serif`;c.textAlign='center';c.fillText(label,x+18,y+50);c.textAlign='left'}
function canvasTag(c,x,y,label,color){c.font='800 18px "Yu Gothic",sans-serif';const w=c.measureText(label).width+34;c.fillStyle=color;c.beginPath();c.roundRect(x,y,w,34,17);c.fill();c.fillStyle='#fff';c.textAlign='center';c.fillText(label,x+w/2,y+23);c.textAlign='left';return w}
function drawComboIcons(c,startX,startY,maxX){
  const context=activeContextTag();
  canvasTag(c,360,116,context.label,context.color);
  let x=startX,y=startY;
  const next=w=>{if(x+w>maxX){x=startX;y+=78}const at=[x,y];x+=w;return at};
  combo.forEach(item=>{
    if(item.type==='direction'){
      const [tx,ty]=next(58);if(item.label==='☆'){c.fillStyle='#f5f7fa';c.font='400 44px "Yu Gothic",sans-serif';c.fillText('☆',tx,ty+42)}else canvasArrow(c,tx,ty+4,42,item.label,item.hold)
    }else if(item.type==='attack'){
      const [tx,ty]=next(64);canvasAttack(c,tx+4,ty+2,item.label)
    }else if(item.type==='separator'){
      const [tx,ty]=next(42);c.fillStyle='#e6333e';c.font='900 40px "Yu Gothic",sans-serif';c.fillText('›',tx+8,ty+40)
    }else if(item.type==='slide'){
      const [tx,ty]=next(48);c.fillStyle='#f5f7fa';c.font='900 42px "Yu Gothic",sans-serif';c.fillText(item.label,tx+2,ty+42)
    }else if(item.type==='stateTag'){
      c.font='800 17px "Yu Gothic",sans-serif';const w=c.measureText(item.label).width+32,[tx,ty]=next(w+12);canvasTag(c,tx,ty+10,item.label,'#326f78')
    }else{
      const code=item.code||named[item.label]?.[0]||item.label,caption=item.caption||named[item.label]?.[1]||'',w=Math.max(105,Math.min(210,caption.length*17));const [tx,ty]=next(w);c.fillStyle='#f5f7fa';c.font='900 29px "Yu Gothic",sans-serif';c.textAlign='center';c.fillText(code,tx+w/2,ty+30);c.fillStyle='#b8c0cc';c.font='700 15px "Yu Gothic",sans-serif';c.fillText(caption,tx+w/2,ty+53);c.textAlign='left'
    }
    if(item.count>1){const [tx,ty]=next(54);c.fillStyle='#f1b84b';c.font='900 23px "Yu Gothic",sans-serif';c.fillText(`×${item.count}`,tx+2,ty+35)}
    (item.annotations||[]).forEach(note=>{c.font='800 14px "Yu Gothic",sans-serif';const w=Math.min(180,c.measureText(note).width+24),[tx,ty]=next(w+8);c.fillStyle='#543b18';c.beginPath();c.roundRect(tx,ty+14,w,27,7);c.fill();c.fillStyle='#ffd98a';c.textAlign='center';c.fillText(note,tx+w/2,ty+33);c.textAlign='left'})
  });
  if(!combo.length){c.fillStyle='#9ca6b5';c.font='700 28px "Yu Gothic",sans-serif';c.fillText('コンボ未入力',startX,startY+36)}
}
function savePngIcons(){
  const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;
  const c=canvas.getContext('2d'),font='"Noto Sans JP","Yu Gothic",sans-serif',stringMode=currentMode==='string';
  const accent=stringMode?'#2aa6a4':'#e6333e',glowColor=stringMode?'#123f46':'#52171d';
  c.fillStyle='#080a0d';c.fillRect(0,0,1200,630);
  const glow=c.createRadialGradient(1050,0,0,1050,0,520);glow.addColorStop(0,glowColor);glow.addColorStop(1,'#080a0d');c.fillStyle=glow;c.fillRect(0,0,1200,630);
  c.fillStyle=accent;c.fillRect(55,50,8,530);c.fillStyle='#171d24';c.beginPath();c.roundRect(63,50,1082,530,22);c.fill();
  c.fillStyle='#f5f7fa';c.font=`900 44px ${font}`;c.fillText($('#character').value.trim()||'CHARACTER',105,125);
  c.fillStyle='#9ca6b5';c.font=`700 17px ${font}`;c.fillText(stringMode?'STRING GUIDE':'COMBO GUIDE',105,155);
  if(!stringMode){c.textAlign='right';c.fillText('DAMAGE',1095,92);c.fillStyle='#f1b84b';c.font=`900 58px ${font}`;c.fillText($('#damage').value||'0',1095,148);c.textAlign='left'}
  c.strokeStyle='#2d3540';c.beginPath();c.moveTo(105,184);c.lineTo(1100,184);c.stroke();drawComboIcons(c,105,205,1095);
  c.beginPath();c.moveTo(105,420);c.lineTo(1100,420);c.stroke();c.fillStyle='#9ca6b5';c.font=`700 16px ${font}`;
  if(stringMode){c.fillText('連携メモ',105,462);c.fillStyle='#f5f7fa';c.font=`500 22px ${font}`;wrap(c,$('#notes').value.trim()||'メモなし',105,500,990,30,2)}else{c.fillText('難易度',105,462);c.fillText('POINT',340,462);c.fillStyle='#f5f7fa';c.font=`800 25px ${font}`;c.fillText($('#difficulty').value,105,503);c.font=`500 21px ${font}`;wrap(c,$('#notes').value.trim()||'注釈なし',340,500,755,30,2)}
  c.fillStyle=accent;c.font=`900 18px ${font}`;c.fillText('TEKKEN 8 COMBO CARD MAKER / CCM',105,555);
  const a=document.createElement('a'),safe=($('#character').value.trim()||'card').replace(/[\\/:*?"<>|]/g,'-'),kind=stringMode?'string':'combo';a.download=`${safe}-${kind}.png`;a.href=canvas.toDataURL('image/png');a.click();say(`${stringMode?'連携':'コンボ'}画像を作成しました`)
}
$('#save').onclick=savePngIcons;
const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),isMobile=isIOS||/Android/i.test(navigator.userAgent);
async function savePngForDevice(){let captured=null;const originalClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){captured=this};try{savePngIcons()}finally{HTMLAnchorElement.prototype.click=originalClick}if(!captured)return;const kind=currentMode==='string'?'連携':'コンボ';if(!isMobile||!navigator.share){captured.click();say(`${kind}画像をダウンロードしました`);return}try{const blob=await fetch(captured.href).then(r=>r.blob()),file=new File([blob],captured.download||'ccm-card.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:`CCM ${kind}カード`});say('共有メニューを開きました。保存先を選べます');return}}catch(error){if(error?.name==='AbortError'){say('保存をキャンセルしました');return}}captured.click();say(`${kind}画像をダウンロードしました`)}
$('#save').onclick=savePngForDevice;
$('#comboMode').onclick=()=>{currentMode='combo';renderMode();say('コンボモードに切り替えました')};
$('#stringMode').onclick=()=>{currentMode='string';renderMode();say('連携モードに切り替えました')};
renderMode();
