const groups={direction:['7','8','9','4','☆','6','1','2','3'],attack:['LP','RP','LK','RK','WP','WK','RP+LK','LP+RK'],separator:['>'],slide:['【','】'],movement:['前ステ','右横移動','左横移動'],state:['立ち途中','横移動中','しゃがみ中'],stage:['壁到達','壁強','ウォールブレイク','フロアブレイク'],system:['トルネード','ヒートバースト','ヒートスマッシュ','ヒートダッシュ','レイジアーツ']};
const titles={direction:'方向',attack:'攻撃',separator:'技の区切り',slide:'スライド入力',movement:'移動',state:'状態',stage:'壁・ステージ',system:'システム'};
const named={'前ステ':['66','前ステ'],'右横移動':['右横','右横移動'],'左横移動':['左横','左横移動'],'立ち途中':['立ち途中','立ち途中'],'横移動中':['横移動中','横移動中'],'しゃがみ中':['しゃがみ中','しゃがみ中'],'壁到達':['W!','壁到達'],'壁強':['W強','壁強'],'ウォールブレイク':['WB','ウォールブレイク'],'フロアブレイク':['FB','フロアブレイク'],'トルネード':['T!','トルネード'],'ヒートバースト':['HB','ヒートバースト'],'ヒートスマッシュ':['HS','ヒートスマッシュ'],'ヒートダッシュ':['HD','ヒートダッシュ'],'レイジアーツ':['RA','レイジアーツ']};
const arrows={'7':'↖','8':'↑','9':'↗','4':'←','☆':'●','6':'→','1':'↙','2':'↓','3':'↘'};
const attackDots={LP:[1,0,0,0],RP:[0,1,0,0],LK:[0,0,1,0],RK:[0,0,0,1],WP:[1,1,0,0],WK:[0,0,1,1],'RP+LK':[0,1,1,0],'LP+RK':[1,0,0,1]};
function attackPad(label){const dots=attackDots[label]||[0,0,0,0];return `<span class="attack-pad" aria-hidden="true">${dots.map(on=>`<i class="${on?'on':''}"></i>`).join('')}</span><small class="attack-label">${label}</small>`}
function iconHtml(label,type,hold=false){if(type==='direction')return `<span class="dir-icon ${label==='☆'?'neutral':`d${label}`} ${hold?'held':''}">${label==='☆'?'☆':'➜'}</span>`;if(type==='attack')return `<span class="attack-set">${attackPad(label)}</span>`;return label}
let combo=[],lastTap=0,timer,directionMode='tap';const $=s=>document.querySelector(s),controls=$('#controls');
Object.entries(groups).forEach(([type,items])=>{const group=document.createElement('div');group.className='group';group.innerHTML=`<div class="group-title">${titles[type]}</div>${type==='direction'?'<div class="direction-mode"><button class="active" data-mode="tap">白抜き・短押し</button><button data-mode="hold">黒・長押し</button></div>':''}<div class="grid ${type==='direction'?'':'two'}"></div>`;const grid=group.querySelector('.grid'),buttons=[];items.forEach(label=>{const b=document.createElement('button');b.className=`cmd ${type}`;const paint=()=>b.innerHTML=iconHtml(label,type,directionMode==='hold');paint();buttons.push(paint);b.setAttribute('aria-label',`${label}を追加`);b.onclick=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),110);const wasHold=type==='direction'&&directionMode==='hold';combo.push({label,type,hold:wasHold});render();say(`${label}${wasHold?'長押し':''} を追加`);if(wasHold){directionMode='tap';group.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode==='tap'));buttons.forEach(p=>p())}};grid.append(b)});if(type==='direction')group.querySelectorAll('[data-mode]').forEach(tab=>tab.onclick=()=>{directionMode=tab.dataset.mode;group.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===tab));buttons.forEach(p=>p())});controls.append(group)});
function draw(el,empty){el.innerHTML='';if(!combo.length){el.textContent=empty;return}combo.forEach(item=>{if(item.type==='separator'){const x=document.createElement('span');x.className='sep';x.textContent='>';el.append(x)}else if(named[item.label]){const x=document.createElement('span');x.className='named';x.innerHTML=`<span>${named[item.label][0]}</span><small>${named[item.label][1]}</small>`;el.append(x)}else{const x=document.createElement('span');x.className=`token ${item.type}-token`;x.innerHTML=iconHtml(item.label,item.type,item.hold);el.append(x)}})}
function render(){draw($('#live'),'ここを見ながら入力できます');draw($('#cardCombo'),'コンボ未入力')}function say(t){$('#status').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent=combo.length?`${combo.length}入力`:'コマンドを入力してください',900)}function undo(){if(!combo.length)return say('これ以上戻せません');const x=combo.pop();render();say(`${x.label} を削除`)}
$('#undo').onclick=undo;$('#clear').onclick=()=>{if(combo.length&&confirm('入力したコンボを全て消しますか？')){combo=[];render();say('全て削除しました')}};$('#toggle').onclick=()=>{const hidden=controls.hidden;controls.hidden=!hidden;$('#toggle').setAttribute('aria-expanded',hidden);$('#chevron').textContent=hidden?'▲':'▼'};
$('#cardCombo').addEventListener('pointerup',()=>{const now=Date.now();if(now-lastTap<360){lastTap=0;undo()}else lastTap=now});$('#cardCombo').ondblclick=e=>{e.preventDefault();undo()};$('#cardCombo').onkeydown=e=>{if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();undo()}};
[['#character','#cardCharacter','CHARACTER'],['#damage','#cardDamage','0'],['#difficulty','#cardDifficulty','★☆☆☆☆']].forEach(([a,b,f])=>{const input=$(a),out=$(b),update=()=>out.textContent=String(input.value).trim()||f;input.oninput=update;input.onchange=update});$('#notes').oninput=e=>$('#cardNotes').textContent=e.target.value.trim()||'注釈を入力するとここに表示されます。';render();
function wrap(c,text,x,y,maxWidth,lineHeight,maxLines=4){let line='',lines=[];for(const ch of [...text]){const test=line+ch;if(c.measureText(test).width>maxWidth&&line){lines.push(line);line=ch}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>c.fillText(i===maxLines-1&&lines.length>maxLines?l.slice(0,-1)+'…':l,x,y+i*lineHeight))}
function savePng(){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const c=canvas.getContext('2d'),font='"Noto Sans JP","Yu Gothic",sans-serif';c.fillStyle='#080a0d';c.fillRect(0,0,1200,630);const glow=c.createRadialGradient(1050,0,0,1050,0,520);glow.addColorStop(0,'#52171d');glow.addColorStop(1,'#080a0d');c.fillStyle=glow;c.fillRect(0,0,1200,630);c.fillStyle='#e6333e';c.fillRect(55,50,8,530);c.fillStyle='#171d24';c.beginPath();c.roundRect(63,50,1082,530,22);c.fill();c.fillStyle='#f5f7fa';c.font=`900 44px ${font}`;c.fillText($('#character').value.trim()||'CHARACTER',105,125);c.fillStyle='#9ca6b5';c.font=`700 17px ${font}`;c.fillText('COMBO GUIDE',105,155);c.textAlign='right';c.fillText('DAMAGE',1095,92);c.fillStyle='#f1b84b';c.font=`900 58px ${font}`;c.fillText($('#damage').value||'0',1095,148);c.textAlign='left';c.strokeStyle='#2d3540';c.beginPath();c.moveTo(105,184);c.lineTo(1100,184);c.stroke();c.fillStyle='#f5f7fa';c.font=`900 38px ${font}`;wrap(c,combo.map(v=>named[v.label]?.[0]||v.label).join('')||'コンボ未入力',105,255,990,54,3);c.beginPath();c.moveTo(105,410);c.lineTo(1100,410);c.stroke();c.fillStyle='#9ca6b5';c.font=`700 16px ${font}`;c.fillText('難易度',105,455);c.fillText('POINT',340,455);c.fillStyle='#f5f7fa';c.font=`800 25px ${font}`;c.fillText($('#difficulty').value,105,495);c.font=`500 21px ${font}`;wrap(c,$('#notes').value.trim()||'注釈なし',340,493,755,30,3);c.fillStyle='#e6333e';c.font=`900 18px ${font}`;c.fillText('TEKKEN 8 COMBO MAKER',105,552);const a=document.createElement('a'),safe=($('#character').value.trim()||'combo').replace(/[\\/:*?"<>|]/g,'-');a.download=`${safe}-combo.png`;a.href=canvas.toDataURL('image/png');a.click();say('PNGを保存しました')}
$('#save').onclick=savePng;
function canvasArrow(c,x,y,size,dir,filled){const angles={'6':0,'3':45,'2':90,'1':135,'4':180,'7':225,'8':270,'9':315};c.save();c.translate(x+size/2,y+size/2);c.rotate((angles[dir]||0)*Math.PI/180);c.beginPath();c.moveTo(-size*.42,-size*.15);c.lineTo(size*.08,-size*.15);c.lineTo(size*.08,-size*.34);c.lineTo(size*.43,0);c.lineTo(size*.08,size*.34);c.lineTo(size*.08,size*.15);c.lineTo(-size*.42,size*.15);c.closePath();if(filled){c.fillStyle='#f5f7fa';c.fill()}else{c.strokeStyle='#f5f7fa';c.lineWidth=2;c.stroke()}c.restore()}
function canvasAttack(c,x,y,label){const dots=attackDots[label]||[0,0,0,0],r=8,gap=20;dots.forEach((on,i)=>{const cx=x+(i%2)*gap+r,cy=y+Math.floor(i/2)*gap+r;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fillStyle=on?'#f5f7fa':'#171d24';c.fill();c.strokeStyle='#f5f7fa';c.lineWidth=1.8;c.stroke()});c.fillStyle='#b8c0cc';c.font='800 14px "Yu Gothic",sans-serif';c.textAlign='center';c.fillText(label,x+18,y+50);c.textAlign='left'}
function drawComboIcons(c,startX,startY,maxX){let x=startX,y=startY;const next=(w)=>{if(x+w>maxX){x=startX;y+=78}const at=[x,y];x+=w;return at};combo.forEach(item=>{if(item.type==='direction'){const [tx,ty]=next(58);if(item.label==='☆'){c.fillStyle='#f5f7fa';c.font='400 44px "Yu Gothic",sans-serif';c.fillText('☆',tx,ty+42)}else canvasArrow(c,tx,ty+4,42,item.label,item.hold)}else if(item.type==='attack'){const [tx,ty]=next(64);canvasAttack(c,tx+4,ty+2,item.label)}else if(item.type==='separator'){const [tx,ty]=next(42);c.fillStyle='#e6333e';c.font='900 40px "Yu Gothic",sans-serif';c.fillText('›',tx+8,ty+40)}else if(item.type==='slide'){const [tx,ty]=next(48);c.fillStyle='#f5f7fa';c.font='900 42px "Yu Gothic",sans-serif';c.fillText(item.label,tx+2,ty+42)}else{const code=named[item.label]?.[0]||item.label,caption=named[item.label]?.[1]||'',w=Math.max(105,Math.min(190,caption.length*17));const [tx,ty]=next(w);c.fillStyle='#f5f7fa';c.font='900 29px "Yu Gothic",sans-serif';c.textAlign='center';c.fillText(code,tx+w/2,ty+30);c.fillStyle='#b8c0cc';c.font='700 15px "Yu Gothic",sans-serif';c.fillText(caption,tx+w/2,ty+53);c.textAlign='left'}});if(!combo.length){c.fillStyle='#9ca6b5';c.font='700 28px "Yu Gothic",sans-serif';c.fillText('コンボ未入力',startX,startY+36)}}
function savePngIcons(){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const c=canvas.getContext('2d'),font='"Noto Sans JP","Yu Gothic",sans-serif';c.fillStyle='#080a0d';c.fillRect(0,0,1200,630);const glow=c.createRadialGradient(1050,0,0,1050,0,520);glow.addColorStop(0,'#52171d');glow.addColorStop(1,'#080a0d');c.fillStyle=glow;c.fillRect(0,0,1200,630);c.fillStyle='#e6333e';c.fillRect(55,50,8,530);c.fillStyle='#171d24';c.beginPath();c.roundRect(63,50,1082,530,22);c.fill();c.fillStyle='#f5f7fa';c.font=`900 44px ${font}`;c.fillText($('#character').value.trim()||'CHARACTER',105,125);c.fillStyle='#9ca6b5';c.font=`700 17px ${font}`;c.fillText('COMBO GUIDE',105,155);c.textAlign='right';c.fillText('DAMAGE',1095,92);c.fillStyle='#f1b84b';c.font=`900 58px ${font}`;c.fillText($('#damage').value||'0',1095,148);c.textAlign='left';c.strokeStyle='#2d3540';c.beginPath();c.moveTo(105,184);c.lineTo(1100,184);c.stroke();drawComboIcons(c,105,205,1095);c.beginPath();c.moveTo(105,420);c.lineTo(1100,420);c.stroke();c.fillStyle='#9ca6b5';c.font=`700 16px ${font}`;c.fillText('難易度',105,462);c.fillText('POINT',340,462);c.fillStyle='#f5f7fa';c.font=`800 25px ${font}`;c.fillText($('#difficulty').value,105,503);c.font=`500 21px ${font}`;wrap(c,$('#notes').value.trim()||'注釈なし',340,500,755,30,2);c.fillStyle='#e6333e';c.font=`900 18px ${font}`;c.fillText('TEKKEN 8 COMBO MAKER',105,555);const a=document.createElement('a'),safe=($('#character').value.trim()||'combo').replace(/[\\/:*?"<>|]/g,'-');a.download=`${safe}-combo.png`;a.href=canvas.toDataURL('image/png');a.click();say('アイコン版PNGを保存しました')}
$('#save').onclick=savePngIcons;
const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
async function savePngForDevice(){let captured=null;const originalClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){captured=this};try{savePngIcons()}finally{HTMLAnchorElement.prototype.click=originalClick}if(!captured)return;try{const blob=await fetch(captured.href).then(r=>r.blob()),file=new File([blob],captured.download||'tekken-combo.png',{type:'image/png'});if(isIOS&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'鉄拳コンボカード'});say('共有メニューを開きました。「画像を保存」を選べます');return}}catch(error){if(error?.name==='AbortError'){say('保存をキャンセルしました');return}}captured.click();say('PNGをダウンロードしました')}
$('#save').onclick=savePngForDevice;
if(isIOS)$('#save').textContent='PNG保存・共有';
