const recipeStorageKey='ccm-recipes-v1',recipeSchemaVersion=1;
function normalizeRecipe(recipe){if(!recipe||typeof recipe!=='object')return null;return{...recipe,schemaVersion:Number(recipe.schemaVersion)||recipeSchemaVersion,mode:recipe.mode==='string'?'string':'combo',combo:Array.isArray(recipe.combo)?recipe.combo:[],notes:String(recipe.notes||'')}}
let savedRecipes=[];try{const stored=JSON.parse(localStorage.getItem(recipeStorageKey)||'[]');savedRecipes=Array.isArray(stored)?stored.map(normalizeRecipe).filter(Boolean):[]}catch(error){savedRecipes=[]}
const mainCharacterStorageKey='ccm-main-character-v1';let mainCharacter='一八';try{mainCharacter=localStorage.getItem(mainCharacterStorageKey)||'一八'}catch(error){mainCharacter='一八'}
const directionDisplayStorageKey='ccm-direction-display-v1';let directionDisplay='arrows';try{directionDisplay=localStorage.getItem(directionDisplayStorageKey)==='numpad'?'numpad':'arrows'}catch(error){directionDisplay='arrows'}
function setDirectionDisplay(mode){directionDisplay=mode==='numpad'?'numpad':'arrows';try{localStorage.setItem(directionDisplayStorageKey,directionDisplay)}catch(error){say('方向表示の設定を保存できませんでした')}document.body.dataset.directionDisplay=directionDisplay;document.querySelectorAll('[data-direction-display]').forEach(button=>{const active=button.dataset.directionDisplay===directionDisplay;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});refreshDirectionDisplays();render();renderMemo();say(directionDisplay==='numpad'?'テンキー表示に切り替えました':'方向キー表示に切り替えました')}
function recipeSnapshot(id,title){return{schemaVersion:recipeSchemaVersion,id,title,updatedAt:Date.now(),mode:currentMode,character:$('#character').value,damage:$('#damage').value,difficulty:$('#difficulty').value,notes:$('#notes').value,startTagId:selectedStartTag.id,stringConditionId:selectedStringCondition.id,combo:JSON.parse(JSON.stringify(combo))}}
function storeRecipes(){try{localStorage.setItem(recipeStorageKey,JSON.stringify(savedRecipes))}catch(error){say('端末の保存領域を利用できませんでした')}}
function updateMainCharacterUI(){const button=$('#setMainCharacter'),selected=$('#character').value,isMain=selected===mainCharacter;button.textContent=isMain?`★ ${selected}（メイン）`:'☆ このキャラをメインに設定';button.classList.toggle('active',isMain);button.disabled=isMain}
function setMainCharacter(){mainCharacter=$('#character').value;try{localStorage.setItem(mainCharacterStorageKey,mainCharacter)}catch(error){say('メインキャラクターを保存できませんでした');return}updateMainCharacterUI();say(`${mainCharacter}をメインキャラクターに設定しました`)}
function persistCurrentRecipe(){if(!currentRecipeId)return;const at=savedRecipes.findIndex(recipe=>recipe.id===currentRecipeId);if(at<0)return;savedRecipes[at]=recipeSnapshot(currentRecipeId,savedRecipes[at].title);storeRecipes();renderRecipeList()}
function renderRecipeList(){const library=$('#recipeLibrary'),list=$('#recipeList');library.hidden=!savedRecipes.length;list.innerHTML='';savedRecipes.forEach(recipe=>{const row=document.createElement('div');row.className=`recipe-row ${recipe.id===currentRecipeId?'active':''}`;const isString=recipe.mode==='string',contextLabel=isString?(stringConditionOptions.find(condition=>condition.id===recipe.stringConditionId)?.label||'ガード後'):(recipe.startTagLabel||startTagOptions.find(tag=>tag.id===recipe.startTagId)?.label||'通常ヒット');const info=document.createElement('div');info.innerHTML=`<strong>${recipe.title}</strong><small>${isString?'連携・':''}${contextLabel}・${recipe.combo?.length||0}入力</small>`;const actions=document.createElement('div');actions.className='recipe-actions';const open=document.createElement('button');open.textContent=recipe.id===currentRecipeId?'編集中':'開く';open.disabled=recipe.id===currentRecipeId;open.onclick=()=>loadRecipe(recipe.id);const rename=document.createElement('button');rename.textContent='名前変更';rename.onclick=()=>renameRecipe(recipe.id);const remove=document.createElement('button');remove.className='recipe-delete';remove.textContent='削除';remove.onclick=()=>deleteRecipe(recipe.id);actions.append(open,rename,remove);row.append(info,actions);list.append(row)})}
function renameRecipe(id){const recipe=savedRecipes.find(item=>item.id===id);if(!recipe)return;const title=prompt('新しいレシピ名を入力してください',recipe.title)?.trim();if(!title)return;recipe.title=title.slice(0,60);recipe.updatedAt=Date.now();storeRecipes();renderRecipeList();say(`レシピ名を「${recipe.title}」に変更しました`)}
function deleteRecipe(id){const recipe=savedRecipes.find(item=>item.id===id);if(!recipe)return;if(!confirm(`「${recipe.title}」を保存一覧から削除しますか？`))return;savedRecipes=savedRecipes.filter(item=>item.id!==id);if(currentRecipeId===id)currentRecipeId=null;storeRecipes();renderRecipeList();say(`${recipe.title}を削除しました`)}
function loadRecipe(id){persistCurrentRecipe();const recipe=savedRecipes.find(item=>item.id===id);if(!recipe)return;currentRecipeId=id;combo=JSON.parse(JSON.stringify(recipe.combo||[]));selectedIndex=null;insertAfterIndex=null;currentMode=recipe.mode||'combo';selectedStartTag=startTagOptions.find(tag=>tag.id===recipe.startTagId)||startTagOptions[0];selectedStringCondition=stringConditionOptions.find(condition=>condition.id===recipe.stringConditionId)||stringConditionOptions[0];$('#character').value=recipe.character||'一八';$('#damage').value=recipe.damage||'0';$('#difficulty').value=recipe.difficulty||'★☆☆☆☆';$('#notes').value=recipe.notes||'';$('#cardCharacter').textContent=$('#character').value;$('#cardDamage').textContent=$('#damage').value;$('#cardDifficulty').textContent=$('#difficulty').value;renderMode();updateCharacterAttacks();updateCharacterCommands();updateCharacterStateTags();updateMainCharacterUI();updateEditor();render();renderRecipeList();say(`${recipe.title}を開きました`)}
function copyRecipe(){if(!combo.length)return say(`コピーする${currentMode==='string'?'連携':'コンボ'}を入力してください`);persistCurrentRecipe();const stamp=Date.now(),character=$('#character').value||'レシピ',kind=currentMode==='string'?'連携':'コンボ';if(!currentRecipeId){const original=recipeSnapshot(`recipe-${stamp}`,`${character} ${kind} 基本`);savedRecipes.push(original)}const clone=recipeSnapshot(`recipe-${stamp+1}`,`${character} ${kind} コピー`);savedRecipes.push(clone);currentRecipeId=clone.id;storeRecipes();renderRecipeList();say('元を残してレシピをコピーしました')}
